### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by TheLizzard** [Jake-Jasper/tkinter-colorpicker#1]
In your code you have something like: `self.R_scale.bind("<ButtonRelease-1>", self.update_col)`. That updates the colour of the canvas when the user releases the left mouse button. You might want to change it to `"<Motion>"` so it will update as the user is dragging.

Also you might want to add `length=200` to `Scale(self.window, orient="horizontal", from_=0, to=255)` to make the scale longer.

**Comment by TheLizzard** [comment]
Also just saying that `self.Ok_button` and `self.close_button` are always `None`. [This](https://stackoverflow.com/a/66385069/11106801) is the reason why.

**Comment by Jake-Jasper** [comment]
I have changed the motion binding, I wasn't aware of that option, thanks!
I did want to have the new window as small as possible but it makes sense to have the length so that you can use all graduations on the scale.
And the last thing I wasn't aware of either so thanks for the improvements.
